name: interval-analysis
version: 0.1.0.0
synopsis: interval analysis
description: interval analysis
category: static-analysis
github: damhiya/interval-analysis
author: damhiya
maintainer: damhiya@gmail.com
copyright: (c) 2022 SoonWon Moon
license: BSD-3-Clause
license-file: LICENSE
extra-source-files: CHANGELOG.md

# common settings
ghc-options: -Wall -Wno-unused-matches
language: GHC2021
default-extensions:
  - OverloadedStrings
  - LambdaCase
dependencies:
  - base >=4.14 && <5.0
  - text >= 2.0
  - containers >= 0.6
  - mtl >= 2.2

executables:
  analysis:
    source-dirs: src
    main: Main.hs
    dependencies: []
